import express from "express";
import OpenAI from "openai";
const app=express(); const port=process.env.PORT||3000;
app.use(express.json({limit:"200kb"})); app.use(express.static("."));
const eu="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/";
const params=(o)=>new URLSearchParams({...o,retmode:"json",tool:"rare_disease_atlas"}).toString();
async function j(url){const r=await fetch(url,{headers:{"User-Agent":"RareDiseaseAtlas/0.2"}});if(!r.ok)throw new Error("Source request failed: "+r.status);return r.json()}
async function search(db,term,max=5){const s=await j(eu+"esearch.fcgi?"+params({db,term,retmax:String(max),sort:"relevance"}));const ids=s.esearchresult?.idlist||[];if(!ids.length)return[];const x=await j(eu+"esummary.fcgi?"+params({db,id:ids.join(",")}));return ids.map(id=>({id,...x.result?.[id]}))}
function cleanPubMed(x){return {pmid:x.id,title:x.title||"",journal:x.fulljournalname||x.source||"",date:x.pubdate||"",authors:(x.authors||[]).slice(0,4).map(a=>a.name),url:"https://pubmed.ncbi.nlm.nih.gov/"+x.id+"/"}}
function cleanClinVar(x){return {variation_id:x.id,title:x.title||"",type:x.obj_type||x.variation_set?.[0]?.variation_type||"",genes:(x.genes||[]).map(g=>g.symbol).filter(Boolean),traits:(x.trait_set||[]).map(t=>t.trait_name).filter(Boolean),url:"https://www.ncbi.nlm.nih.gov/clinvar/variation/"+x.id+"/"}}
app.get("/api/health",(req,res)=>res.json({ok:true,openai_configured:Boolean(process.env.OPENAI_API_KEY)}));
app.get("/api/evidence",async(req,res)=>{try{const disease=String(req.query.disease||"").slice(0,120),neighbor=String(req.query.neighbor||"").slice(0,120);if(!disease||!neighbor)return res.status(400).json({error:"disease and neighbor are required"});const literatureQuery='("'+disease+'"[Title/Abstract]) AND ("'+neighbor+'"[Title/Abstract])';const [pub,cv1,cv2]=await Promise.all([search("pubmed",literatureQuery,6),search("clinvar",disease+"[trait name]",4),search("clinvar",neighbor+"[trait name]",4)]);res.json({query:{disease,neighbor},retrieved_at:new Date().toISOString(),sources:{pubmed:pub.map(cleanPubMed),clinvar:[...cv1.map(cleanClinVar),...cv2.map(cleanClinVar)]}})}catch(e){res.status(502).json({error:e.message})}});
app.post("/api/challenge",async(req,res)=>{try{if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:"OPENAI_API_KEY is not configured on the server"});const {disease,neighbor,evidence}=req.body||{};if(!disease||!neighbor||!evidence)return res.status(400).json({error:"disease, neighbor and evidence are required"});const client=new OpenAI();const prompt=`You are the adversarial evidence reviewer for a rare-disease research atlas. Evaluate a proposed research connection between "${disease}" and "${neighbor}" using ONLY the supplied evidence metadata. Do not invent biomedical facts. Missing abstracts/full text means you must be cautious. Return ONLY valid JSON with keys: verdict (one of "survives_challenge","not_supported_yet"), rationale (string), support (array of strings), counter_evidence (array of strings), missing_evidence (array of strings), decisive_experiment (string), source_ids (array of PMID or ClinVar variation IDs actually used). Evidence: ${JSON.stringify(evidence)}`;const out=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5",input:prompt});let text=out.output_text.trim().replace(/^\`\`\`json\s*/,"").replace(/\`\`\`$/,"").trim();let result;try{result=JSON.parse(text)}catch{result={verdict:"not_supported_yet",rationale:text,support:[],counter_evidence:[],missing_evidence:["Model output was not structured JSON."],decisive_experiment:"Expert review of the retrieved evidence is required.",source_ids:[]}}res.json({model:process.env.OPENAI_MODEL||"gpt-5",generated_at:new Date().toISOString(),result})}catch(e){res.status(502).json({error:e.message})}});
app.listen(port,()=>console.log("Rare Disease Atlas running on http://localhost:"+port));